version: '3.8'

services:
  nrega-bookmarks:
    build: .
    container_name: nrega_bookmarks_app
    restart: unless-stopped
    ports:
      - "6006:5000"
    env_file:
      - .env
    volumes:
      - ./instance:/app/instance